.PHONY: clean All

All:
	@echo "----------Building project:[ Friends - Debug ]----------"
	@cd "Friends" && "$(MAKE)" -f  "Friends.mk"
clean:
	@echo "----------Cleaning project:[ Friends - Debug ]----------"
	@cd "Friends" && "$(MAKE)" -f  "Friends.mk" clean
