.PHONY: clean All

All:
	@echo "----------Building project:[ Challenge - Debug ]----------"
	@"$(MAKE)" -f  "Challenge.mk"
clean:
	@echo "----------Cleaning project:[ Challenge - Debug ]----------"
	@"$(MAKE)" -f  "Challenge.mk" clean
