.PHONY: clean All

All:
	@echo "----------Building project:[ Vectors - Debug ]----------"
	@"$(MAKE)" -f  "Vectors.mk"
clean:
	@echo "----------Cleaning project:[ Vectors - Debug ]----------"
	@"$(MAKE)" -f  "Vectors.mk" clean
