.PHONY: clean All

All:
	@echo "----------Building project:[ RangeBasedForLoop - Debug ]----------"
	@"$(MAKE)" -f  "RangeBasedForLoop.mk"
clean:
	@echo "----------Cleaning project:[ RangeBasedForLoop - Debug ]----------"
	@"$(MAKE)" -f  "RangeBasedForLoop.mk" clean
