.PHONY: clean All

All:
	@echo "----------Building project:[ MPGFunctionExceptionClasses - Debug ]----------"
	@cd "MilesPerGallonFunctionExceptionClasses" && "$(MAKE)" -f  "MPGFunctionExceptionClasses.mk"
clean:
	@echo "----------Cleaning project:[ MPGFunctionExceptionClasses - Debug ]----------"
	@cd "MilesPerGallonFunctionExceptionClasses" && "$(MAKE)" -f  "MPGFunctionExceptionClasses.mk" clean
