.PHONY: clean All

All:
	@echo "----------Building project:[ PassingPointers2 - Debug ]----------"
	@cd "PassingPointers2" && "$(MAKE)" -f  "PassingPointers2.mk"
clean:
	@echo "----------Cleaning project:[ PassingPointers2 - Debug ]----------"
	@cd "PassingPointers2" && "$(MAKE)" -f  "PassingPointers2.mk" clean
