.PHONY: clean All

All:
	@echo "----------Building project:[ Room_cleaning - Debug ]----------"
	@cd "Room_cleaning" && "$(MAKE)" -f  "Room_cleaning.mk"
clean:
	@echo "----------Cleaning project:[ Room_cleaning - Debug ]----------"
	@cd "Room_cleaning" && "$(MAKE)" -f  "Room_cleaning.mk" clean
